<a href="https://colab.research.google.com/github/StefanTesmanovic/Chess/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = [
     'This is the first document',
     'This document is the second document.',
     'And this is the third one',
     'Is this the first document?',
 ]
file_name = "crnamacka.txt"
X = vectorizer.fit_transform(get_sentences_from_file(file_name))
#X = vectorizer.fit_transform(corpus)
print(X.toarray())
vectorizer.get_feature_names_out()
X = X.toarray()
print(X.shape)
vectorizer.get_feature_names_out()

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(42, 291)


array(['ali', 'analysis', 'aproksimira', 'apstraktivne', 'apstraktivno',
       'automatic', 'based', 'bi', 'biblioteke', 'biblioteku',
       'bibloiteku', 'bih', 'bilo', 'bitnost', 'bitnosti', 'bolje',
       'broj', 'chatgpt', 'countvectorizer', 'd0', 'da', 'dataset',
       'datu', 'decomposition', 'dela', 'dijagonali', 'dijagonalna',
       'dimenzija', 'dimenzionalnosti', 'do', 'dobija', 'dobijaju',
       'dobijamo', 'dobijemo', 'dobijenoj', 'dobiti', 'dok', 'dovesti',
       'doći', 'ekstraktivna', 'ekstraktivne', 'elemenata', 'evaluiranje',
       'funkciju', 'greške', 'ili', 'ima', 'imaju', 'indexing', 'ispod',
       'ista', 'istih', 'isto', 'iz', 'izaberemo', 'izabranog', 'između',
       'izvuku', 'javiti', 'je', 'jedne', 'jednu', 'jer', 'jezik', 'kad',
       'kao', 'ključna', 'knjiga', 'književnih', 'koja', 'koje', 'koji',
       'kojoj', 'koliko', 'kolona', 'kolone', 'kom', 'korak', 'koren',
       'koristi', 'koristio', 'koristiti', 'korišćenje', 'korišćenjem',
       

In [9]:
def get_sentences_from_file(filename):
    sentences = []

    with open(filename, 'r') as file:
        text = file.read()
        sentences = text.split('.')
        sentences = [sentence.strip() for sentence in sentences if sentence.strip() != '']

    return sentences




In [ ]:
import numpy as np
U, S, Vt = np.linalg.svd(np.transpose(X))
print(U.shape,"\n")
print(S,"\n")
print(Vt)

In [ ]:
def LSI(U, S, Vt):
    pass